"""add temporal fields to identity

Revision ID: e2873e9cf9fb
Revises: 658018bb07cc
Create Date: 2026-03-23 07:46:19.060986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2873e9cf9fb'
down_revision: Union[str, None] = '658018bb07cc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('beliefs', sa.Column('valid_from', sa.DateTime(), nullable=True))
    op.add_column('beliefs', sa.Column('valid_until', sa.DateTime(), nullable=True))
    op.add_column('preferences', sa.Column('valid_from', sa.DateTime(), nullable=True))
    op.add_column('preferences', sa.Column('valid_until', sa.DateTime(), nullable=True))
    op.add_column('style_profiles', sa.Column('valid_from', sa.DateTime(), nullable=True))
    op.add_column('style_profiles', sa.Column('valid_until', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('style_profiles', 'valid_until')
    op.drop_column('style_profiles', 'valid_from')
    op.drop_column('preferences', 'valid_until')
    op.drop_column('preferences', 'valid_from')
    op.drop_column('beliefs', 'valid_until')
    op.drop_column('beliefs', 'valid_from')
    # ### end Alembic commands ###
